Areas/Administration/Controllers/MemberController.cs
using cloudscribe.Pagination.Models;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tela.Areas.Administration.Models.Member;
using Tela.Data.Core;
using Tela.Data.Organisation;
using Tela.Models;
using Tela.Services;
namespace Tela.Areas.Administration.Controllers;
//TODO:b 292. Add MemberController to Administration Area (extend from Administration Controlller)
public class MemberController : AdministrationController
{
    //TODO:b 293. Add LibraryService to MemberController (constructor injection)
    private readonly LibraryService _libraryService; 
    public MemberController(ApplicationDbContext context, ILogger<MemberController> logger, LibraryService libraryService) 
        : base(context, logger)
    {
        _libraryService = libraryService;
    }
    /*TODO:b 298. Install Nuget Packages for Pagination
     * https://www.nuget.org/packages/cloudscribe.Web.Pagination
     * https://www.nuget.org/packages/cloudscribe.Pagination.Models
     */
    //TODO:b 303. Add GET: Administration/Member/Index
    //TODO:b 304 Add .table-responsive class to site.scss
    public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 5)
    => View(new PagedResult<Tela.Models.MemberDTO>
    {
        Data = (await _libraryService.GetMembersAsync<Tela.Models.MemberDTO>(LibraryId, (pageSize * pageNumber) - pageSize, pageSize)).ToList(),
        TotalItems = await _libraryService.GetMemberCountAsync(LibraryId),
        PageNumber = pageNumber,
        PageSize = pageSize
    });
    //TODO:b 295. Add GET: Administration/Member/Create 
    public IActionResult Create() => View();
    //TODO:b 296. Add POST: Administration/Member/Create (import Create model)
    [HttpPost]
    public async Task<IActionResult> Create(Create m)
    {
        if (ModelState.IsValid)
        {
            try
            {
                //TODO:b 297. Run and verfiy the create action (check the database for a new user)
                await _libraryService.RegisterMemberAsync(LibraryId,m.Email!,m.FirstName!,m.LastName!);
                return RedirectToAction("Index");
            }
            catch (DomainRuleException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message, ex);
                //TODO:b 319. Add Loxa as indication of error for end user if general exception occurs
                //The causality of the exception is logged for the developer
                ModelState.AddModelError("", Q.Loxa);
            }           
        }
        return View(m);
    }
    //TODO:b 393. Add GET: Administration/Member/Search (searchTerm)
    [HttpGet]
    public async Task<IActionResult> Search(string searchTerm)
    => Json(await _libraryService.GetMembersAsync<MemberDTO>(LibraryId,searchTerm));
  
}

Areas/Administration/Controllers/ReferenceController.cs
using cloudscribe.Pagination.Models;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Tela.Areas.Administration.Models.Reference;
using Tela.Data.Core;
using Tela.Data.Organisation.Inventory;
using Tela.Models;
using Tela.Services;
namespace Tela.Areas.Administration.Controllers;
//TODO:b 347. Add ReferenceController to Administration area
public class ReferenceController : AdministrationController
{
    private readonly ReferenceService _referenceService;
    public ReferenceController(ApplicationDbContext context, ILogger<ReferenceController> logger, ReferenceService referenceService)
        : base(context, logger)
    {
        _referenceService = referenceService;
        //TODO:b 360. Mapster for Edit model is configured in constructor
        TypeAdapterConfig<Reference,Edit>.NewConfig().Ignore(d => d.Books);        
    }           
    //TODO:b 352. Add Index action to ReferenceController
    [HttpGet]
    public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 5) => View(new PagedResult<ReferenceDTO>
    {
        Data = (await _referenceService.GetReferencesAsync<ReferenceDTO>(LibraryId,Librarian.Id,TemporalisLibri.Forgetful,(pageSize * pageNumber) - pageSize, pageSize)).ToList(),
        TotalItems = await _referenceService.GetReferenceCountAsync(LibraryId),
        PageNumber = pageNumber,
        PageSize = pageSize
    });
    //TODO:b 363. Add Details GET action to ReferenceController
    [HttpGet]
    public async Task<IActionResult> Details(int id)
    => View(await _referenceService.GetReferenceAsync<ReferenceDTO>(LibraryId, Librarian.Id, id, TemporalisLibri.AllTransactionsAndRestorations)); 
    //TODO:b 349. Add Create GET/POST actions to ReferenceController
    //Also add IsUniqueISBN action for remote validation called from Create.cs
    [HttpGet]
    public IActionResult Create() => View(new Create { Books = 10 });
    [HttpPost]
    public async Task<IActionResult> Create(Create m)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _referenceService.AddReferenceAsync(LibraryId, Librarian.Id, m.Title, m.ISBN, m.Author, m.Books);
                return RedirectToAction("Index");
            }
            catch (DomainRuleException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message, ex);
                ModelState.AddModelError("",Q.Loxa);
            }
        }
        return View(m);
    }
    [HttpGet]
    public async Task<IActionResult> IsUniqueISBN(string isbn)
    => await _referenceService.IsUniqueISBN(LibraryId, isbn) ? Json("ISBN already exists") : Json(true);
    //TODO:b 361. Add Edit GET/POST actions to ReferenceController
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var m = await _referenceService.GetReferenceAsync<Edit>(LibraryId, Librarian.Id, id, TemporalisLibri.Forgetful); 
        if (m == null)
        {
            return NotFound();
        }
        return View(m);
    }
    [HttpPost]
    public async Task<IActionResult> Edit(Edit m)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _referenceService.UpdateReferenceAsync(LibraryId, Librarian.Id, m.Title, m.ISBN, m.Author);
                return RedirectToAction(nameof(this.Index));
            }
            catch (DomainRuleException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message, ex);
                ModelState.AddModelError("",Q.Loxa);
            }
        }
        return View(m);
    }
}

Areas/Administration/Views/Shared/_Nav.cshtml
@{
   //TODO:b 250. Add partial _Nav.cshtml file to /Areas/Administration/Views/Shared (Administration area)
}
<nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-1">
    <div class="container-fluid m-0">
        @{
            /*TODO:b 338b. Add _Toggle paritial view to Administration/Views/Shared/_Nav.cshtml*/
        }
        <partial name="_Toggle" />
        <partial name="_Bibliotheca" />
        <a class="nav-link d-flex align-center py-1 px-3" asp-area="" asp-controller="Home" asp-action="Index" title="Bibliotheca+Procuratio~Systema">
            <span class="material-symbols-outlined">hub</span>
            <span>~B-P+S </span>
        </a>
        <div class="d-inline-flex">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a title="Administration" class="nav-link" asp-area="Administration" asp-controller="Home" asp-action="Index">
                        <span class="material-symbols-outlined" id="t-settings">
                            settings
                        </span>
                    </a>
                </li> 
                @{/*TODO:b 306. Add Member Index link to Administration Views Shared _Nav.cshtml*/}
                <li class="nav-item">
                    <a title="Members" class="nav-link" asp-area="Administration" asp-controller="Member" asp-action="Index">
                        <span class="material-symbols-outlined" id="t-members">diversity_1</span>
                    </a>
                </li>
                @{
                    /*TODO:b 354. Add Reference Index link to Administration Views Shared _Nav.cshtml*/
                }
                <li class="nav-item">
                    <a title="Book References" class="nav-link" asp-area="Administration" asp-controller="Reference" asp-action="Index">
                        <span class="material-symbols-outlined" id="t-references">
                            qr_code_scanner
                        </span>
                    </a>
                </li>
                @{
                    /*TODO:b 388. Add Transaction Index link to Administration Views Shared _Nav.cshtml*/
                }
                <li title="Book Transactions" class="nav-item">
                    <a class="nav-link" asp-area="Administration" asp-controller="Transaction" asp-action="Index">
                        <span class="material-symbols-outlined" id="t-transactions">
                            manage_history
                        </span>
                    </a>
                </li>
                @{
                    /*TODO:b 411. Add Transaction Hold/Loan links to Administration Views Shared _Nav.cshtml*/
                }
                <li class="nav-item">
                    <a title="Hold" class="nav-link"  asp-area="Administration" asp-controller="Transaction" asp-action="Hold">
                        <span class="material-symbols-outlined" id="t-hold">
                            hand_bones
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a title="Process Loan" class="nav-link" asp-area="Administration" asp-controller="Transaction" asp-action="Loan">
                        <span class="material-symbols-outlined" id="t-loan">
                            auto_stories
                        </span>
                    </a>
                </li>
                @{
                    /*TODO:b 417. Add Restoration Index link to Administration Views Shared _Nav.cshtml*/
                }
                <li class="nav-item">
                    <a title="Restorations" class="nav-link" style="padding: 0.35rem;" asp-area="Administration" asp-controller="Restoration" asp-action="Index">
                        <span class="material-symbols-outlined" id="t-restore">
                            construction
                        </span>
                    </a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>