Areas/Administration/Controllers/BookController.cs
using cloudscribe.Pagination.Models;
using Microsoft.AspNetCore.Mvc;
using Tela.Data.Core;
using Tela.Data.Organisation.Inventory;
using Tela.Models;
using Tela.Services;
namespace Tela.Areas.Administration.Controllers;
//TODO:b 369. Add BookController to Administration Area 
public class BookController : AdministrationController
{
    private readonly ReferenceService _referenceService;
    public BookController(ApplicationDbContext context, ILogger<BookController> logger, ReferenceService catalogueService)
        : base(context, logger)
    {
        _referenceService = catalogueService;
    }
    //TODO:b 372. Add Index Action to BookController in Administration Area
    //id = ReferenceId
    public async Task<IActionResult> Index(int id, int pageNumber = 1, int pageSize = 5)
    => View(new PagedResult<BookDTO>
    {
        Data = (await _referenceService.GetBooksAsync<BookDTO>(LibraryId,Librarian.Id,id,TemporalisLibri.ActiveTransactionsAndRestorations, (pageSize * pageNumber) - pageSize, pageSize)).ToList(),
        TotalItems = await _referenceService.GetBookCountAsync(LibraryId, id),
        PageNumber = pageNumber,
        PageSize = pageSize
    });
    //TODO:b 375. Add Create Action to BookController
    [HttpPost]
    public async Task<IActionResult> Create(int id)
    {
        try
        {
            if (!Q.CoinFlip(65)) { 
                throw new DomainRuleException("Coffee Composition Exception");
            }
            var reference = await _context.References.FindAsync(id);
            if (reference == null) return NotFound();
            var b = reference.RegisterBook();
            await _context.SaveChangesAsync();
            TempData["Message"] = $"Book {b.UID} has been replicated";
            TempData["Alert"] = "success";
        }
        catch (DomainRuleException ex)
        {
            TempData["Message"] = Q.W;
            TempData["Alert"] = "danger";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            TempData["Message"] = Q.W;
            TempData["Alert"] = "danger";
        }
        return RedirectToAction(nameof(Index), new { id });    
    }
    //TODO:b 377. Add Details Action to BookController
    //id = UID
    public async Task<IActionResult> Details(Guid id) 
        => View(await _referenceService.GetBookAsync<BookDTO>(LibraryId, Librarian.Id,id,TemporalisLibri.ActiveTransactionsAndRestorations));
    //TODO:b 394. Add GET: Administration/Book/Search (searchTerm)
    [HttpGet]
    public async Task<IActionResult> Search(string searchTerm, State.Types? state = null)
    => Json((await _referenceService.GetBooksAsync<BookDTO>(LibraryId, searchTerm)).Where(b => !state.HasValue || b.State == state.Value));

}

Areas/Administration/Controllers/RestorationController.cs
using cloudscribe.Pagination.Models;
using Microsoft.AspNetCore.Mvc;
using Tela.Areas.Administration.Models.Restoration;
using Tela.Data.Core;
using Tela.Models;
using Tela.Services;
namespace Tela.Areas.Administration.Controllers;
//TODO:b 414. Add RestorationController to Administration
public class RestorationController : AdministrationController
{
    private readonly RestorationService _restorationService;
    public RestorationController(ApplicationDbContext context, ILogger<RestorationController> logger, RestorationService restorationService )
        : base(context, logger) 
    {
        _restorationService = restorationService;   
    }
    //TODO:b 415. Add Index method to RestorationController
    public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 5)
   => View(new PagedResult<RestorationDTO>
   {
       Data = (await _restorationService.GetRestorationsAsync<RestorationDTO>(LibraryId,Librarian.Id,TemporalisLibri.AllRestorations,(pageSize * pageNumber) - pageSize, pageSize)).ToList(),
       TotalItems = await _restorationService.GetRestorationCountAsync(LibraryId,Librarian.Id, TemporalisLibri.AllRestorations),
       PageNumber = pageNumber,
       PageSize = pageSize
   });
    //TODO:b 421. Add administration-restoration-schedule.js
    //TODO:b 422. Add Schedule GET/POST methods to RestorationController
    [HttpGet]
    public async Task<IActionResult> Schedule(Guid? uid)
    => View(new Schedule
    {
        Start = DateTime.Now.AddDays(7),
        End = DateTime.Now.AddDays(14),
        Book = uid.HasValue ? await _restorationService.GetBookAsync<BookDTO>(LibraryId,uid.Value) : default!
    });
    [HttpPost]
    public async Task<IActionResult> Schedule(Schedule m)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _restorationService.ScheduleRestorationAsync(LibraryId, Librarian, m.Book.UID!.Value, m.Start!.Value, m.End!.Value);
                return RedirectToAction(nameof(Index));
            }
            catch (DomainRuleException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message, ex);
                ModelState.AddModelError("", Q.Loxa);
            }
        }
        return View(m);
    }
    //TODO:b 420. Add DateIsInFuture method to RestorationController
    [AcceptVerbs("GET", "POST")]
    public IActionResult DateIsInFuture(DateTime? start, DateTime? end)
    => Json((start.IsAndIsNotFuturistic() || end.IsAndIsNotFuturistic())
        ? $"{(start.IsAndIsNotFuturistic() ? "Start" : "End")} must be in this particular dimension's future." : true
    );
}

Areas/Administration/Views/Book/Details.cshtml
@model BookDTO
@{
    //TODO:b 381. Add Administration Book Details View
    ViewData["Title"] = $"{@Model.Title!.ToUpper()} : {Model.UID}";
}
<div class="accordion accordion-flush" id="book-accordion">  
    <div class="accordion-item">
        <h2 class="accordion-header p-0 w-100">  
            <button id="btn-tau-cal" title="TAU" class="accordion-button collapsed p-1" type="button" data-bs-toggle="collapse" data-bs-target="#tau-cal" aria-expanded="false" aria-controls="#tau-cal">
                <span style="font-size:3em;line-height:1rem;" class="ms-1 war-p mb-1">
                    &#120591;<span style="font-size:small">au</span>
                </span>
            </button>    
        </h2>
        <div id="tau-cal" class="accordion-collapse" data-bs-parent="#book-accordion">
            <div class="accordion-body p-1">
               <div id="tau" style="max-height:70vh"></div>
            </div>
        </div>
    </div>
    <div class="accordion-item">     
        <h2 class="accordion-header">
            <button class="accordion-button p-1 border-0" type="button" data-bs-toggle="collapse" data-bs-target="#book" aria-expanded="true" aria-controls="book">
                <span class="war-p">@Model.Title!.ToUpper()</span>
            </button>
        </h2>
        <div id="book" class="accordion-collapse" data-bs-parent="#book-accordion">
            <div class="accordion-body p-2">
                <dl>
                    <dt>UID</dt>
                    <dd>@Model.UID</dd>
                    <dt>ISBN</dt>
                    <dd>@Model.ISBN</dd>
                    <dt>Loans</dt>
                    <dd>@Model.LoanCount @(Model.IsOnLoan ? "*On Loan" : "")</dd>
                    <dt>On Hold</dt>
                    <dd><span class="@(Model.IsOnHold ? "text-warning": "")">@(Model.IsOnHold ? "Yes": "No") </span></dd>
                    <dt>Being Restored</dt>
                    <dd>
                        @if (Model.IsBeingRestored)
                        {
                            <span class="text-warning">YES</span>
                        }
                        else
                        {
                            <span class="d-flex justify-content-start gap-1">                             
                                <span>NO</span>
                                <a title="Schedule Restoration: @Q.T" asp-area="Administration" asp-controller="Restoration" asp-action="Schedule" asp-route-uid="@Model.UID">
                                    <span class="material-symbols-outlined">construction</span>
                                </a>
                            </span>                           
                        }                       
                    </dd>
                    <dt>Status</dt>
                    <dd>@Model.State.ToString()</dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<input type="hidden" asp-for="UID" />
@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.14/index.global.min.js"></script>
    <environment include="Development">
        <script src="/js/administration-book-details.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://quiz-engin-cdn-dtbyasb5ekdvc6h5.z01.azurefd.net/js/administration-book-details.min.js"></script>
    </environment>
}

Areas/Administration/Views/Book/Index.cshtml
@model PagedResult<BookDTO>
@{
    //TODO:b 373. Add Index.cshtml to Administration Book Views 
    ViewData["Title"] = Html.Raw($"&#128020; &#128020; &#128020; ");
    var alrightyThen = Html.Raw($"Union &cup; Book &#128214; with Library &#127963; books {"{}"} =  &#127963; &cup; {"{&#128214;}"}");
}
@if (!string.IsNullOrWhiteSpace(TempData["Message"]?.ToString()))
{
    <div class="alert alert-@TempData["Alert"] alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @{/*TODO:b 466. Update TempData Message to use Html Raw Book Index */}
        @Html.Raw(TempData["Message"])
    </div>
}
<div class="table-responsive">
    <table>
        <thead>
            <tr>
                <th>UID</th>
                <th>ISBN</th>
                <th>Reference</th>
                <th>State</th>
                <th class="text-end">
                    <form asp-action="Create">
                        <input type="hidden" name="Id" value="@ViewContext.RouteData.Values["id"]" />
                        <button type="submit" class="d-inline-flex gap-1 align-middle btn btn-primary btn-sm" asp-action="Create" title="@alrightyThen">
                            &#127963;&cup;{&#128214;}
                        </button>
                    </form>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var b in Model.Data)
            {
                string c = "15vw";
                <tr>
                    <td title="@b.UID" style="max-width:@c">@b.UID</td>
                    <td title="@b.ISBN" style="max-width:@c">@b.ISBN</td>
                    <td title="@b.Title" style="max-width:@c">@b.Title</td>
                    <td title="@b.State" style="max-width:@c">@b.State</td>
                    <td title="Actions" style="max-width:35vw" class="d-flex justify-content-end gap-1">
                        <a asp-action="Details" asp-route-id="@b.UID" title="Book Details: @Q.T" class="mx-1">
                            <i class="bi bi-binoculars-fill"></i>
                        </a>
                        <a title="Process Loan: @Q.T" asp-area="Administration" asp-controller="Transaction" asp-action="Loan" asp-route-uid="@b.UID">
                            <span class="material-symbols-outlined">
                                auto_stories
                            </span>
                        </a>
                        <a title="Hold: @Q.T" asp-area="Administration" asp-controller="Transaction" asp-action="Hold" asp-route-uid="@b.UID">
                            <span class="material-symbols-outlined">
                                hand_bones
                            </span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="d-flex justify-content-center">
    <partial name="_Pager" model='Model.GetPagerModel<BookDTO>("Book","Index")' />
</div>
<div class="war-p text-sm-center" style="cursor:help" data-wibble="@Q.R">
    &#8734; &#127963; &#128020; Book &#128020; Book &#128020; Book &#128020; && &#128056; Read I.T. &#128056; Read I.T. &#128056; Read I.T. &#128056; && &#128020; Book &#128020; Book &#128020; Book &#128020; &#127963; &#8734;
</div>
<div class="scene" style="display:none">
    <div class="book">
        <p class="war-p">Photons</p>
        <p class="war-p">2 Gravitons</p>
        <p class="war-p">V.&#8734; (4+2)</p>
    </div>
    <div class="black-hole"><div class="supermassive"></div></div>
</div>
@section Scripts {
    <environment include="Development">
        <script src="/js/administration-book-index.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://quiz-engin-cdn-dtbyasb5ekdvc6h5.z01.azurefd.net/js/administration-book-index.min.js"></script>
    </environment>
}